### ISSUE TITLE
Modularized :: Impossible to open / Failed to concatenate segments:

### ISSUE THREAD

**Issue by gniknalu** [roflcoopter/viseron#333] opened 2022-03-10 23:18 UTC
For every recording I'm getting a `Impossible to open` error followed by a `Failed to concatenate segments` error. Video is being recorded so I'm not sure what is going on.
```
[2022-03-10 16:22:52] [INFO    ] [viseron.components.ffmpeg.recorder.FrontEast2] - Starting recorder
[2022-03-10 16:22:52] [INFO    ] [viseron.components.nvr.FrontEast2] - Starting motion detector
[2022-03-10 16:22:54] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 9
[2022-03-10 16:22:55] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 8
[2022-03-10 16:22:56] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 7
[2022-03-10 16:22:57] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 6
[2022-03-10 16:22:58] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 5
[2022-03-10 16:22:59] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 4
[2022-03-10 16:23:00] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 3
[2022-03-10 16:23:01] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 2
[2022-03-10 16:23:02] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 1
[2022-03-10 16:23:03] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 0
[2022-03-10 16:23:03] [INFO    ] [viseron.components.nvr.FrontEast2] - Pausing motion detector
[2022-03-10 16:23:03] [INFO    ] [viseron.components.ffmpeg.recorder.FrontEast2] - Stopping recorder
[concat @ 0x55ffb625e500] Impossible to open 'file:/segments/FrontEast2/20220310162243.mp4'
pipe:: No such file or directory
[2022-03-10 16:23:16] [ERROR   ] [viseron.components.ffmpeg.recorder.FrontEast2] - Failed to concatenate segments: Command '['ffmpeg', '-hide_banner', '-loglevel', 'error', '-y', '-protocol_whitelist', 'file,pipe', '-f', 'concat', '-safe', '0', '-i', '-', '-c:v', 'h264', '-c:a', 'copy', '-movflags', '+faststart', '/recordings/FrontEast2/2022-03-10/FrontE_2022-03-10-162252.mp4']' returned non-zero exit status 1.
[2022-03-10 16:41:35] [INFO    ] [viseron.components.ffmpeg.recorder.FrontEast2] - Starting recorder
[2022-03-10 16:41:35] [INFO    ] [viseron.components.nvr.FrontEast2] - Starting motion detector
[2022-03-10 16:41:37] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 9
[2022-03-10 16:41:38] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 8
[2022-03-10 16:41:39] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 7
[2022-03-10 16:41:40] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 6
[2022-03-10 16:41:41] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 5
[2022-03-10 16:41:42] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 4
[2022-03-10 16:41:43] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 3
[2022-03-10 16:41:44] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 2
[2022-03-10 16:41:45] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 1
[2022-03-10 16:41:46] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 0
[2022-03-10 16:41:46] [INFO    ] [viseron.components.nvr.FrontEast2] - Pausing motion detector
[2022-03-10 16:41:46] [INFO    ] [viseron.components.ffmpeg.recorder.FrontEast2] - Stopping recorder
[2022-03-10 16:42:02] [INFO    ] [viseron.components.ffmpeg.recorder.FrontEast2] - Starting recorder
[2022-03-10 16:42:02] [INFO    ] [viseron.components.nvr.FrontEast2] - Starting motion detector
[2022-03-10 16:42:03] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 9
[2022-03-10 16:42:04] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 8
[2022-03-10 16:42:05] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 7
[2022-03-10 16:42:06] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 6
[2022-03-10 16:42:07] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 5
[2022-03-10 16:42:08] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 4
[2022-03-10 16:42:09] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 3
[2022-03-10 16:42:10] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 2
[2022-03-10 16:42:11] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 1
[2022-03-10 16:42:12] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 0
[2022-03-10 16:42:12] [INFO    ] [viseron.components.nvr.FrontEast2] - Pausing motion detector
[2022-03-10 16:42:12] [INFO    ] [viseron.components.ffmpeg.recorder.FrontEast2] - Stopping recorder
[2022-03-10 16:42:16] [ERROR   ] [viseron.components.ffmpeg.recorder.FrontEast2] - Could not get duration for: /segments/FrontEast2/20220310164133.mp4. Error: /segments/FrontEast2/20220310164133.mp4: No such file or directory

[2022-03-10 16:42:16] [ERROR   ] [viseron.components.ffmpeg.recorder.FrontEast2] - Could not get duration for: /segments/FrontEast2/20220310164139.mp4. Error: /segments/FrontEast2/20220310164139.mp4: No such file or directory

[concat @ 0x563b39df6500] Impossible to open 'file:/segments/FrontEast2/20220310164153.mp4'
pipe:: No such file or directory
[2022-03-10 16:42:16] [ERROR   ] [viseron.components.ffmpeg.recorder.FrontEast2] - Failed to concatenate segments: Command '['ffmpeg', '-hide_banner', '-loglevel', 'error', '-y', '-protocol_whitelist', 'file,pipe', '-f', 'concat', '-safe', '0', '-i', '-', '-c:v', 'h264', '-c:a', 'copy', '-movflags', '+faststart', '/recordings/FrontEast2/2022-03-10/FrontE_2022-03-10-164202.mp4']' returned non-zero exit status 1.
```

**Comment by roflcoopter** [comment] 2022-03-11 08:33
Strange, i am not seeing this on my end. Can you post your config?
There was a bug in the functionality that retries setup of a component that fails, which resulted in the domain being setup multiple times.
That mihgt be the cause. I pushed a fix for it yesterday

**Comment by gniknalu** [comment] 2022-03-11 13:48
> Strange, i am not seeing this on my end. Can you post your config? There was a bug in the functionality that retries setup of a component that fails, which resulted in the domain being setup multiple times. That mihgt be the cause. I pushed a fix for it yesterday

I'll refresh my docker later today. This is my config (I switched to deepstack to see if I can get better performance)

```
cat config.yaml
ffmpeg:
  camera:
    BackEast:
       name: Back_East
       host: !secret camera_ip_back_east
       username: !secret camera_us_back_east
       password: !secret camera_pw_back_east
       path: /cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif/trackID=0
       port: 554
       fps: 29
       recorder:
         idle_timeout: 1
         extension: mkv
         filename_pattern: 'BackE_%Y-%m-%d-%H%M%S'
         lookback: 12
         retain: 90
         thumbnail:
           filename_pattern: 'BackE_%Y-%m-%d-%H%M%S'
    FrontEast2:
       name: Front_East2
       host: !secret camera_ip_front_east2
       username: !secret camera_us_front_east2
       password: !secret camera_pw_front_east2
       path: /cam/realmonitor?channel=1&subtype=0&proto=Private3
       port: 80
       fps: 29
       recorder:
         idle_timeout: 10
         codec: h264
         filename_pattern: 'FrontE_%Y-%m-%d-%H%M%S'
         lookback: 7
         retain: 90
         thumbnail:
           filename_pattern: 'FrontE_%Y-%m-%d-%H%M%S'
    FrontWest:
       name: Front_West
       host: !secret camera_ip_front_west
       username: !secret camera_us_front_west
       password: !secret camera_pw_front_west
       path: /Streaming/Channels/101?transportmode=unicast&profile=Profile_1
       port: 554
       fps: 25
       recorder:
         idle_timeout: 10
         codec: h264
         filename_pattern: 'FrontW_%Y-%m-%d-%H%M%S'
         lookback: 7
         retain: 90
         thumbnail:
           filename_pattern: 'FrontW_%Y-%m-%d-%H%M%S'

deepstack:
  host: xxxx.xxxx.xxxx.xxxx
  port: 5000
  object_detector:
    image_width: 1024
    image_height: 1024
    cameras:
      FrontEast2:
        fps: 1
        scan_on_motion_only: false
        labels:
          - label: person
            trigger_recorder: true
          - label: dog
            trigger_recorder: true
          - label: cat
            trigger_recorder: true
          - label: truck
            trigger_recorder: true
            require_motion: true
          - label: car
            trigger_recorder: true
            require_motion: true
      FrontWest:
        fps: 1
        labels:
          - label: person
            trigger_recorder: true
          - label: dog
            trigger_recorder: true
          - label: cat
            trigger_recorder: true
          - label: truck
            trigger_recorder: true
            require_motion: true
          - label: car
            trigger_recorder: true
            require_motion: true
      BackEast:
        fps: 2


background_subtractor:
  motion_detector:
    cameras:
      FrontEast2:
        fps: 1
        mask:
          - coordinates:
              - x: 957
                y: 1515
              - x: 957
                y: 676
              - x: 1186
                y: 438
              - x: 2100
                y: 438
              - x: 2684
                y: 590
              - x: 2684
                y: 1
              - x: 1
                y: 1
              - x: 1
                y: 1515
      FrontWest:
        fps: 1
        mask:
          - coordinates:
              - x: 294
                y: 0
              - x: 1920
                y: 0
              - x: 1920
                y: 206
              - x: 1651
                y: 136
              - x: 1120
                y: 114
              - x: 321
                y: 233
          - coordinates:
              - x: 1
                y: 537
              - x: 1
                y: 1080
              - x: 1920
                y: 1080
              - x: 1920
                y: 810
              - x: 1278
                y: 870
              - x: 526
                y: 1015
      BackEast:
        fps: 1
        mask:
          - coordinates:
              - x: 1914
                y: 1
              - x: 320
                y: 1
              - x: 320
                y: 148
              - x: 872
                y: 33
              - x: 1914
                y: 174


nvr:
  FrontEast2:
  FrontWest:
  BackEast:

webserver:

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  username: !secret mqtt_us
  password: !secret mqtt_pw
  client_id: viseron
  home_assistant:

logger:
  default_level: info
  logs:
    viseron.components.data_stream: info
    viseron.components.background_subtractor: info
    viseron.components.mog2: info
```

**Comment by gniknalu** [comment] 2022-03-11 23:15
After updating this morning, I see a couple more. This is the most recent:

```
[2022-03-11 14:44:20] [INFO    ] [viseron.components.ffmpeg.recorder.FrontEast2] - Starting recorder
[2022-03-11 14:44:21] [INFO    ] [viseron.components.nvr.FrontEast2] - Starting motion detector
[2022-03-11 14:44:24] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 9
[2022-03-11 14:44:25] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 8
[2022-03-11 14:44:26] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 7
[2022-03-11 14:44:27] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 6
[2022-03-11 14:44:28] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 5
[2022-03-11 14:44:29] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 4
[2022-03-11 14:44:30] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 3
[2022-03-11 14:44:31] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 2
[2022-03-11 14:44:32] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 1
[2022-03-11 14:44:33] [INFO    ] [viseron.components.nvr.FrontEast2] - Stopping recording in: 0
[2022-03-11 14:44:33] [INFO    ] [viseron.components.nvr.FrontEast2] - Pausing motion detector
[2022-03-11 14:44:33] [INFO    ] [viseron.components.ffmpeg.recorder.FrontEast2] - Stopping recorder
[concat @ 0x55dfa2405500] Impossible to open 'file:/segments/FrontEast2/20220311144331.mp4'
pipe:: No such file or directory
pipe:: Input/output error
    Last message repeated 7 times
[2022-03-11 14:44:44] [ERROR   ] [viseron.components.ffmpeg.recorder.FrontEast2] - Could not get duration for: /segments/FrontEast2/20220311144302.mp4. Error: /segments/FrontEast2/20220311144302.mp4: No such file or directory

[2022-03-11 14:44:44] [ERROR   ] [viseron.components.ffmpeg.recorder.FrontEast2] - Could not get duration for: /segments/FrontEast2/20220311144256.mp4. Error: /segments/FrontEast2/20220311144256.mp4: No such file or directory

[2022-03-11 14:44:45] [ERROR   ] [viseron.components.ffmpeg.recorder.FrontEast2] - Could not get duration for: /segments/FrontEast2/20220311144416.mp4. Error: /segments/FrontEast2/20220311144416.mp4: No such file or directory

[2022-03-11 14:44:45] [ERROR   ] [viseron.components.ffmpeg.recorder.FrontEast2] - Could not get duration for: /segments/FrontEast2/20220311144346.mp4. Error: /segments/FrontEast2/20220311144346.mp4: No such file or directory

[2022-03-11 14:44:45] [ERROR   ] [viseron.components.ffmpeg.recorder.FrontEast2] - Could not get duration for: /segments/FrontEast2/20220311144316.mp4. Error: /segments/FrontEast2/20220311144316.mp4: No such file or directory

[2022-03-11 14:44:45] [ERROR   ] [viseron.components.ffmpeg.recorder.FrontEast2] - Could not get duration for: /segments/FrontEast2/20220311144322.mp4. Error: /segments/FrontEast2/20220311144322.mp4: No such file or directory

[2022-03-11 14:44:45] [ERROR   ] [viseron.components.ffmpeg.recorder.FrontEast2] - Could not get duration for: /segments/FrontEast2/20220311144356.mp4. Error: /segments/FrontEast2/20220311144356.mp4: No such file or directory

[2022-03-11 14:44:45] [ERROR   ] [viseron.components.ffmpeg.recorder.FrontEast2] - Could not get duration for: /segments/FrontEast2/20220311144411.mp4. Error: /segments/FrontEast2/20220311144411.mp4: No such file or directory

[2022-03-11 14:44:45] [ERROR   ] [viseron.components.ffmpeg.recorder.FrontEast2] - Could not get duration for: /segments/FrontEast2/20220311144311.mp4. Error: /segments/FrontEast2/20220311144311.mp4: No such file or directory

[2022-03-11 14:44:45] [WARNING ] [viseron.components.ffmpeg.recorder.FrontEast2] - Could not find matching start segment. Using earliest possible
[concat @ 0x559a3962c500] Impossible to open 'file:/segments/FrontEast2/20220311144246.mp4'
pipe:: No such file or directory
[2022-03-11 14:44:45] [ERROR   ] [viseron.components.ffmpeg.recorder.FrontEast2] - Failed to concatenate segments: Command '['ffmpeg', '-hide_banner', '-loglevel', 'error', '-y', '-protocol_whitelist', 'file,pipe', '-f', 'concat', '-safe', '0', '-i', '-', '-c:v', 'h264', '-c:a', 'copy', '-movflags', '+faststart', '/recordings/FrontEast2/2022-03-11/FrontE_2022-03-11-144420.mp4']' returned non-zero exit status 1.
```

**Comment by TannedCung** [comment] 2022-04-02 00:17
I have the same problem with `roflcoopter/viseron:latest` image running on a RPi3. The same image works fine with my PC

**Comment by roflcoopter** [comment] 2022-12-19 14:13
This was fixed recently in v2, seemed to happen when multiple recordings started back 2 back.
Please open a new issue if it still persists

**Closed by roflcoopter** 2022-12-19 14:13 UTC
