### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by Sloth-on-meth** [roflcoopter/viseron#116] opened 2021-01-26 12:20 UTC
```[2021-01-26 13:19:37] [root                    ] [INFO    ] - -------------------------------------------
[2021-01-26 13:19:37] [root                    ] [INFO    ] - Initializing...
[2021-01-26 13:19:37] [root                    ] [INFO    ] - Initializing NVR threads
[2021-01-26 13:19:40] [lib.camera.achtertuin   ] [WARNING ] - ffprobe failed to get stream information
[2021-01-26 13:19:40] [root                    ] [INFO    ] - Initialization complete
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/src/viseron/lib/camera.py", line 423, in capture_pipe
    if motion_frame_number % motion_decoder_interval_calculated == 0:
ZeroDivisionError: integer division or modulo by zero

```

my config: 

```
# See the README for the full list of configuration options.
cameras:
  - name: achtertuin
    host: 192.168.178.113
    port: 554
    username: xxxx
    password: xxxx
    path: /
    stream_format: rtsp

# MQTT is optional
#mqtt:
#  broker: <ip address or hostname of broker>
#  port: <port the broker listens on>
#  username: <if auth is enabled>
#  password: <if auth is enabled>
```

**Comment by Sloth-on-meth** [comment] 2021-01-26 12:44
fixed by adding height and width in the config

**Comment by roflcoopter** [comment] 2021-01-28 06:50
Will take a look at this soon, closing as its a duplicate of #58

**Closed by roflcoopter** 2021-01-28 06:50 UTC
